package core.schedule.ui;

import core.utils.Hour;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.border.Border;

/**
 *
 * @author kiira
 */
public class HoursStrip extends javax.swing.JPanel {

    /** Creates new form HoursStrip */
    public HoursStrip( int hoursHeight, int timeFraction ) {
        initComponents();

        //creamos los labels
        int repetitions = Hour.HOURS * Hour.MINS / timeFraction;
        Hour h = new Hour();
        JLabel label;
        Border border = BorderFactory.
                createMatteBorder( 0, 0, 1, 1, Color.black );
        Dimension dim;

        for ( int i = 0; i < repetitions; i++ ) {
            //creamos el label y lo dimensionamos
            label = new JLabel( String.format( "<html><br/>%s</html>", h.
                    toString() ) );
            label.setVerticalAlignment( JLabel.TOP );

            dim = new Dimension( label.getPreferredSize().width + 10,
                                 hoursHeight );
            label.setMaximumSize( dim );
            label.setPreferredSize( dim );

            label.setBorder( border );


            this.jPMain.add( label );

            h.addMins( timeFraction );
        }

    }

    public HoursStrip( int hoursHeight ) {
        this( hoursHeight, 60 );
    }

    public HoursStrip() {
        this( 150 );
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings ( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPMain = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPMain.setName("jPMain"); // NOI18N
        jPMain.setLayout(new javax.swing.BoxLayout(jPMain, javax.swing.BoxLayout.Y_AXIS));
        add(jPMain, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPMain;
    // End of variables declaration//GEN-END:variables
}
