/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewTaskDialog.java
 *
 * Created on 22-ago-2012, 20:58:04
 */
package core.schedule.ui;

import core.schedule.task.Task;
import core.utils.Hour;
import java.util.Date;
import javax.swing.JFrame;

/**
 *
 * @author a1
 */
public class NewTaskDialog extends javax.swing.JDialog {

    private Task task;

    /** Creates new form NewTaskDialog */
    public NewTaskDialog( JFrame parent, Hour init, Hour end ) {
        super( parent, true );

        this.setTitle( "Add new Task");
        
        initComponents();

        this.jSInitHour.setValue( init.toDate() );
        this.jSEndHour.setValue( end.toDate() );

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings ( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        vFNorth = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        hFEast = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jPMain = new javax.swing.JPanel();
        jLDescription = new javax.swing.JLabel();
        jTFDescription = new javax.swing.JTextField();
        vFDescription = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jLInitHour = new javax.swing.JLabel();
        jSInitHour = new javax.swing.JSpinner();
        hFHours = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jLEndHour = new javax.swing.JLabel();
        jSEndHour = new javax.swing.JSpinner();
        vFButtons = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(32767, 15));
        jBClose = new javax.swing.JButton();
        jBSave = new javax.swing.JButton();
        vFSouth = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        hFWest = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setModal(true);
        setResizable(false);

        vFNorth.setName("vFNorth"); // NOI18N
        getContentPane().add(vFNorth, java.awt.BorderLayout.NORTH);

        hFEast.setName("hFEast"); // NOI18N
        getContentPane().add(hFEast, java.awt.BorderLayout.EAST);

        jPMain.setName("jPMain"); // NOI18N
        jPMain.setLayout(new java.awt.GridBagLayout());

        jLDescription.setText("Description:");
        jLDescription.setName("jLDescription"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPMain.add(jLDescription, gridBagConstraints);

        jTFDescription.setColumns(20);
        jTFDescription.setName("jTFDescription"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPMain.add(jTFDescription, gridBagConstraints);

        vFDescription.setName("vFDescription"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPMain.add(vFDescription, gridBagConstraints);

        jLInitHour.setText("Initial Hour");
        jLInitHour.setName("jLInitHour"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        jPMain.add(jLInitHour, gridBagConstraints);

        jSInitHour.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.MINUTE));
        jSInitHour.setEditor(new javax.swing.JSpinner.DateEditor(jSInitHour, "HH:mm"));
        jSInitHour.setName("jSInitHour"); // NOI18N
        jSInitHour.setPreferredSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPMain.add(jSInitHour, gridBagConstraints);

        hFHours.setName("hFHours"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPMain.add(hFHours, gridBagConstraints);

        jLEndHour.setText("End Hour");
        jLEndHour.setName("jLEndHour"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        jPMain.add(jLEndHour, gridBagConstraints);

        jSEndHour.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.MINUTE));
        jSEndHour.setEditor(new javax.swing.JSpinner.DateEditor(jSEndHour, "HH:mm"));
        jSEndHour.setName("jSEndHour"); // NOI18N
        jSEndHour.setPreferredSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPMain.add(jSEndHour, gridBagConstraints);

        vFButtons.setName("vFButtons"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPMain.add(vFButtons, gridBagConstraints);

        jBClose.setText("Close");
        jBClose.setName("jBClose"); // NOI18N
        jBClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCloseActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPMain.add(jBClose, gridBagConstraints);

        jBSave.setText("Save");
        jBSave.setName("jBSave"); // NOI18N
        jBSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSaveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPMain.add(jBSave, gridBagConstraints);

        getContentPane().add(jPMain, java.awt.BorderLayout.CENTER);

        vFSouth.setName("vFSouth"); // NOI18N
        getContentPane().add(vFSouth, java.awt.BorderLayout.SOUTH);

        hFWest.setName("hFWest"); // NOI18N
        getContentPane().add(hFWest, java.awt.BorderLayout.WEST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCloseActionPerformed
        this.dispose();

    }//GEN-LAST:event_jBCloseActionPerformed

    private void jBSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSaveActionPerformed
        this.task = new Task( Hour.fromDate( (Date)this.jSInitHour.getValue() ),
                              Hour.fromDate( (Date)this.jSEndHour.getValue() ),
                              jTFDescription.getText() );
        
        this.jBCloseActionPerformed( evt );
    }//GEN-LAST:event_jBSaveActionPerformed

    Task getTask() {
        return this.task;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler hFEast;
    private javax.swing.Box.Filler hFHours;
    private javax.swing.Box.Filler hFWest;
    private javax.swing.JButton jBClose;
    private javax.swing.JButton jBSave;
    private javax.swing.JLabel jLDescription;
    private javax.swing.JLabel jLEndHour;
    private javax.swing.JLabel jLInitHour;
    private javax.swing.JPanel jPMain;
    private javax.swing.JSpinner jSEndHour;
    private javax.swing.JSpinner jSInitHour;
    private javax.swing.JTextField jTFDescription;
    private javax.swing.Box.Filler vFButtons;
    private javax.swing.Box.Filler vFDescription;
    private javax.swing.Box.Filler vFNorth;
    private javax.swing.Box.Filler vFSouth;
    // End of variables declaration//GEN-END:variables
}
