/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package core.schedule.ui;

import core.task.Task;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Paint;
import java.awt.Point;
import javax.swing.BorderFactory;

/**
 *
 * @author kiira
 */
public class TaskPanel extends javax.swing.JPanel {

    private Color baseColor;
    private Task task;

    /** Creates new form TaskPanel */
    public TaskPanel( Task task, int hoursHeight, int timeFraction, Color color ) {
        initComponents();
        this.task = task;
        this.baseColor = color;

        //calculamos y seteamos la altura de acuerdo a los parámetros
        int height = Math.
                round(
                (float)task.getDurationInMinutes() * hoursHeight / timeFraction );
        this.setPreferredSize( new Dimension( this.getPreferredSize().width,
                                              height ) );

        //creamos y asignamos el borde
        this.setBorder( BorderFactory.
                createMatteBorder( 0, 0, 1, 0, Color.black ) );

        //seteamos la descripción de la task y cambiamos el color del mismo
        this.jLDescription.setText( task.getDescription() );
        this.jLDescription.setForeground(
                ( color.getRGB() < Color.black.getRGB() / 2 )
                ? Color.white
                : Color.black );

        //asignamos en el tooltip los horarios reales
        this.setToolTipText( String.format( "Desde las %s hasta las %s",
                                            task.getInitHour(), task.
                getEndHour() ) );
    }

    public TaskPanel( Task task, int timeFraction, int hoursHeight ) {
        this( task, hoursHeight, timeFraction, new Color( 254, 79, 79 ) );
    }

    public TaskPanel( int height ) {
        initComponents();
        this.setPreferredSize( new Dimension( this.getPreferredSize().width,
                                              height ) );
        this.setBorder( BorderFactory.
                createMatteBorder( 0, 0, 1, 0, Color.black ) );
    }

    public TaskPanel() {
        this( 100 );
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings ( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLDescription = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jLDescription.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLDescription.setName("jLDescription"); // NOI18N
        add(jLDescription, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLDescription;
    // End of variables declaration//GEN-END:variables

    @Override
    protected void paintComponent( Graphics g ) {
        super.paintComponent( g );

        //si no hay task, no ponemos ningún color
        if ( this.task == null )
            return;

        //casteamos el graphics
        Graphics2D g2 = (Graphics2D)g;

        //generamos el gradiente y lo asignamos        
        Color firstColor = this.baseColor.brighter();
        Color secondColor = this.baseColor.darker();

        Paint gradient = new GradientPaint(
                new Point( 0, this.getHeight() * 1 / 4 ), firstColor,
                new Point( 0, this.getHeight() ), secondColor );

        g2.setPaint( gradient );

        //pintamos
        g2.fillRect( 0, 0, this.getWidth(), this.getHeight() );

        //dibujamos un borde del color base
        g2.setPaint( this.baseColor );

        g2.drawLine( 0, 0, 0, this.getHeight() );
        g2.drawLine( 0, 0, this.getWidth(), 0 );
        g2.drawLine( 0, this.getHeight(), this.getWidth(), this.getHeight() );
        g2.drawLine( this.getWidth(), 0, this.getWidth(), this.getHeight() );
    }

}
