/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package core.schedule.ui;

import core.task.Task;
import java.awt.Color;
import java.awt.Dimension;

/**
 *
 * @author kiira
 */
public class TaskPanel extends javax.swing.JPanel {

    private Task task;

    /** Creates new form TaskPanel */
    public TaskPanel( Task task, int hoursHeight, int timeFraction, Color color ) {
        initComponents();
        this.task = task;

        int height = task.getDurationInMinutes() * hoursHeight / timeFraction;
        this.setPreferredSize( new Dimension( this.getPreferredSize().width,
                                              height ) );
        this.setBackground( color );

        this.jLDescription.setText( task.getDescription() );
    }

    public TaskPanel( Task task, int timeFraction, int hoursHeight ) {
        this( task, hoursHeight, timeFraction, new Color( 254, 79, 79 ) );
    }

    public TaskPanel( int height ) {
        initComponents();
        this.setPreferredSize( new Dimension( this.getPreferredSize().width,
                                              height ) );
    }

    public TaskPanel() {
        this( 100 );
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings ( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLDescription = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jLDescription.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLDescription.setName("jLDescription"); // NOI18N
        add(jLDescription, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLDescription;
    // End of variables declaration//GEN-END:variables
}
